### ISSUE TITLE
打怪没有经验，然后提示这个

### ISSUE THREAD

**Issue by Niguangz** [Leader-txt/Legend_p#7]
at Z.Expressions.EvalManager.get_DefaultContext()
   at Z.Expressions.Eval.Execute[TResult](String code, Object parameters)
   at Legend.MainPlugin.OnNPCKilled(NpcKilledEventArgs args)

**Comment by Leader-txt** [comment]
看看配置文件

**Comment by Niguangz** [comment]
{
  "MaxSkill": 10,
  "MaxSkillLevel": 10,
  "ExpRate": 0.2,
  "ExpRateUp": "init+level/100*2",
  "Exp": 300,
  "LevelUp": "exp*2^level",
  "MaxLevel": 40,
  "Jobs": [
    {
      "Name": "弓箭手",
      "Levels": [
        {
          "num": 0,
          "Damage": 0.0,
          "SkillNum": 0,
          "SkillMax": 0,
          "Buff": [
            0
          ]
        }
      ],
      "Damage": 0.05,
      "DamageUp": "init+level/100*2",
      "SkillNum": 2,
      "SkillNumUp": "init+level*2"
    }
  ],
  "Skills": [
    {
      "Projs": [
        {
          "ProjID": 1,
          "Rate": 0.8,
          "RateUp": "init+level/100*2",
          "Num": {
            "Item1": 5,
            "Item2": 10
          },
          "Span": {
            "Item1": 0,
            "Item2": 0
          },
          "X": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "Y": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "Direct": false,
          "VX": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "VY": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "Damage": 10,
          "DamageUp": "init+level*2",
          "KnockBack": 5.0,
          "KnockBackUp": "init+level*2"
        }
      ],
      "Name": "木",
      "Note": "1",
      "Rate": 0.2,
      "RateUp": "init +level/100*2",
      "Price": 2,
      "PriceUp": "init+level*2",
      "Jobs": [
        ""
      ],
      "Weapons": [
        0
      ],
      "HealRate": 0.2,
      "HealRateUp": "init +level/100*2",
      "HealArea": 300,
      "AreaUp": "init*level",
      "Heal": 10,
      "HealUp": "init+level*10",
      "UptakeRate": 0.2,
      "UptakeRateUp": "init +level/100*2",
      "Uptake": 10,
      "UptakeUp": "init+level*2",
      "TakeRate": 0.5,
      "TakeRateUp": "init+level/100*2",
      "TakeArea": 300,
      "TakeAreaUp": "init*level"
    }
  ]
}

**Comment by Niguangz** [comment]
就默认的，不知道什么问题用不了

**Comment by Niguangz** [comment]
对了，一开始是有经验的，选择好职业就出问题了了

**Comment by Leader-txt** [comment]
远古项目了，可能是配置文件问题，建议用旧版release，有中文配置文件

**Comment by Niguangz** [comment]
中文也用了，也不行，可能是我配置搞错了

**Comment by Leader-txt** [comment]
来张报错截图吧

**Comment by Niguangz** [comment]
![1](https://github.com/Leader-txt/Legend_p/assets/146617207/8c956a8f-155b-4c78-8de5-55942e555ade)

**Comment by Niguangz** [comment]
{
  "初始最多可学习技能数": 10,
  "最高技能等级": 10,
  "初始经验值获取比例 获取的经验值=击杀怪物血量x此比例": 0.2,
  "经验值获取比例计算公式 init-初始比例 level-等级": "init+level/100*2",
  "初始经验值": 300,
  "升级至下级所需经验计算公式(exp:初始经验值,level:玩家当前等级)": "exp*2^level",
  "最高等级": 40,
  "职业": [
    {
      "职业名称": "弓箭手",
      "特殊等级升级需求": [
        {
          "等级": 0,
          "额外增加的伤害点数 (0-1的数值)": 0.0,
          "额外给予的技能点数": 0,
          "额外给予的技能学习位数量": 0,
          "额外给予的buff": [
            0
          ]
        }
      ],
      "初始伤害点数 (0-1的数值)": 0.05,
      "升级时奖励伤害点数计算公式 init-初始伤害点数 level-等级": "init+level/100*2",
      "初始奖励技能点数": 2,
      "升级时奖励技能点数计算公式 init-初始奖励技能点数 level-等级": "init+level*2"
    }
  ],
  "技能": [
    {
      "弹幕": [
        {
          "弹幕id": 1,
          "初始生成概率(0-1的值)": 0.8,
          "生成概率计算公式 init-初始生成概率 level-等级": "init+level/100*2",
          "生成数量范围(最小值，最大值)": {
            "Item1": 5,
            "Item2": 10
          },
          "多个弹幕生成时间间隔范围(最小值，最大值)单位：ms": {
            "Item1": 0,
            "Item2": 0
          },
          "弹幕生成位置范围X 以下均以玩家为原点": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "弹幕生成位置范围Y": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "是否以最近敌对npc为攻击目标": false,
          "弹幕生成速度X分矢量范围": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "弹幕生成速度y分矢量范围": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "初始弹幕伤害": 10,
          "弹幕伤害计算公式 init-初始伤害 level-弹幕等级": "init+level*2",
          "初始弹幕击退": 5.0,
          "弹幕击退计算公式 init-初始击退 level-弹幕等级": "init+level*2"
        }
      ],
      "技能名称": "",
      "技能备注": "",
      "初始技能触发概率": 0.2,
      "技能触发概率计算公式 init-初始技能触发概率 level-等级": "init +level/100*2",
      "初始技能学习点数": 2,
      "升级所需点数计算公式 init-初始技能学习点数 level-等级": "init+level*2",
      "允许使用的职业名称 若该数组中包含‘-1’则所有职业均可使用": [
        "弓箭手"
      ],
      "允许使用的武器id 若该数组中包含-1，则所有职业均可使用": [
        -1
      ],
      "初始治疗触发概率 0-1的值": 0.2,
      "治疗概率计算公式 init-初始治疗触发概率 level-等级": "init +level/100*2",
      "初始治疗半径": 300,
      "治疗半径计算公式 init-初始治疗半径 level-等级": "init*level",
      "初始治疗点数": 10,
      "治疗点数计算公式 init-初始治疗点数 level-等级": "init+level*10",
      "初始吸血概率 0-1的值": 0.2,
      "吸血概率计算公式 init-初始治疗概率 level-等级": "init +level/100*2",
      "初始吸血点数": 10,
      "吸血点数计算公式 init-初始吸血点数 level-等级": "init+level*2",
      "初始吸血转化率": 0.5,
      "吸血转化率计算公式 init-初始吸血转化率 level-等级": "init+level/100*2",
      "初始吸血半径": 300,
      "吸血半径计算公式 init-初始吸血半径 level-等级": "init*level"
    }
  ]
}

**Comment by Niguangz** [comment]
{
  "初始最多可学习技能数": 10,
  "最高技能等级": 10,
  "初始经验值获取比例 获取的经验值=击杀怪物血量x此比例": 0.2,
  "经验值获取比例计算公式 init-初始比例 level-等级": "init+level/100*2",
  "初始经验值": 300,
  "升级至下级所需经验计算公式(exp:初始经验值,level:玩家当前等级)": "exp*2^level",
  "最高等级": 40,
  "职业": [
    {
      "职业名称": "弓箭手",
      "特殊等级升级需求": [
        {
          "等级": 0,
          "额外增加的伤害点数 (0-1的数值)": 0.0,
          "额外给予的技能点数": 0,
          "额外给予的技能学习位数量": 0,
          "额外给予的buff": [
            0
          ]
        }
      ],
      "初始伤害点数 (0-1的数值)": 0.05,
      "升级时奖励伤害点数计算公式 init-初始伤害点数 level-等级": "init+level/100*2",
      "初始奖励技能点数": 2,
      "升级时奖励技能点数计算公式 init-初始奖励技能点数 level-等级": "init+level*2"
    }
  ],
  "技能": [
    {
      "弹幕": [
        {
          "弹幕id": 1,
          "初始生成概率(0-1的值)": 0.8,
          "生成概率计算公式 init-初始生成概率 level-等级": "init+level/100*2",
          "生成数量范围(最小值，最大值)": {
            "Item1": 5,
            "Item2": 10
          },
          "多个弹幕生成时间间隔范围(最小值，最大值)单位：ms": {
            "Item1": 0,
            "Item2": 0
          },
          "弹幕生成位置范围X 以下均以玩家为原点": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "弹幕生成位置范围Y": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "是否以最近敌对npc为攻击目标": false,
          "弹幕生成速度X分矢量范围": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "弹幕生成速度y分矢量范围": {
            "Item1": -10.0,
            "Item2": 10.0
          },
          "初始弹幕伤害": 10,
          "弹幕伤害计算公式 init-初始伤害 level-弹幕等级": "init+level*2",
          "初始弹幕击退": 5.0,
          "弹幕击退计算公式 init-初始击退 level-弹幕等级": "init+level*2"
        }
      ],
      "技能名称": "",
      "技能备注": "",
      "初始技能触发概率": 0.2,
      "技能触发概率计算公式 init-初始技能触发概率 level-等级": "init +level/100*2",
      "初始技能学习点数": 2,
      "升级所需点数计算公式 init-初始技能学习点数 level-等级": "init+level*2",
      "允许使用的职业名称 若该数组中包含‘-1’则所有职业均可使用": [
        "弓箭手"
      ],
      "允许使用的武器id 若该数组中包含-1，则所有职业均可使用": [
        -1
      ],
      "初始治疗触发概率 0-1的值": 0.2,
      "治疗概率计算公式 init-初始治疗触发概率 level-等级": "init +level/100*2",
      "初始治疗半径": 300,
      "治疗半径计算公式 init-初始治疗半径 level-等级": "init*level",
      "初始治疗点数": 10,
      "治疗点数计算公式 init-初始治疗点数 level-等级": "init+level*10",
      "初始吸血概率 0-1的值": 0.2,
      "吸血概率计算公式 init-初始治疗概率 level-等级": "init +level/100*2",
      "初始吸血点数": 10,
      "吸血点数计算公式 init-初始吸血点数 level-等级": "init+level*2",
      "初始吸血转化率": 0.5,
      "吸血转化率计算公式 init-初始吸血转化率 level-等级": "init+level/100*2",
      "初始吸血半径": 300,
      "吸血半径计算公式 init-初始吸血半径 level-等级": "init*level"
    }
  ]
}

**Comment by Hex4gonForc3** [comment]
![Screenshot_2024-03-15-12-19-43-27](https://github.com/Leader-txt/Legend_p/assets/153827257/62e3c358-eb7a-4ee1-8b4f-609bf15b9fdf)
Bro why this error
